/* jshint esversion: 6 */

export const DASHBOARD_RELOAD_UPDATE = 'DASHBOARD_RELOAD_UPDATE';
export const DASHBOARD_SET_RANGES = 'DASHBOARD_SET_RANGES';
export const DASHBOARD_SET_FILTERS = 'DASHBOARD_SET_FILTERS';
export const SET_DISPLAY_WIDGET_FORM = 'SET_DISPLAY_WIDGET_FORM';
export const SET_WIDGET_FIELD = 'SET_WIDGET_FIELD';
